kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: postgres-pv-volume 
  labels: 
    type: local 
    app: postgres 
spec: 
  storageClassName: minikube-hostpath
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: "/opt/postgres/data" 
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: postgres-pv-claim 
  labels:
    app: postgres 
spec: 
  storageClassName: minikube-hostpath 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi
