apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 30002
      port: 30002
      nodePort: 30002
  selector:
    app: front
