apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-network-policy
spec:
  podSelector:
    matchLabels:
      app: api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
            - { key: app, operator: In, values: [front, postgres] }
  egress:
    - to:
        - podSelector:
            matchExpressions:
            - { key: app, operator: In, values: [front, postgres] }
